### PR TITLE
added fishing guide to docs

### PR DESCRIPTION
**Pull request by PepperTheVixen**
I've added a fishing guide to the docs. I'm not 100% happy with it, but this is the best I could put together after several hours of tearing my hair out and trying to fish without a fishing mod. The most difficult part of providing written instructions are the audio queue descriptions. I've tried to supplement some of them with links to videos of the sounds. I don't like this solution since videos can get taken down and websites can have problems, but I don't have any other solution on hand at this time. I welcome criticism and refinement to make this guide better.

### Guides And Docs

- Added a fishing guide to the docs. This explains how to fish as a blind Stardew Access player and offers recommendations and resources to make the fishing minigame less painful.

### CODE REVIEW

**Comment by khanshoaib3** [comment]
@PepperTheVixen The changelog in the subheadings are supposed to be in unordered list, I should've mentioned that in the pull request template.
And It'll also be best if we not duplicate changelogs, so in this case the one in Feature Updates is not relevant.

Thank you for the updates though :)

**Comment by PepperTheVixen** [comment]
Changelog edited :3

**Comment by khanshoaib3** [comment]
@PepperTheVixen The PR branch is apparently behind 10 or so commits from `development` branch.
Can you please rebase the PR branch with dev branch and then force push.

**Comment by PepperTheVixen** [comment]
Should be fixed now. Sorry about that

**Pull request merged**
